import React from 'react';
import { Bullets, DocScreen, Prose, Section } from '../src/components/DocScreen';

/**
 * Terms of Use, reached from Settings > Terms of Use.
 *
 * Deliberately specific about what the app does, because a generic template would be
 * both longer and less true. Placeholders that a deployment has to fill in are
 * gathered at the top of the file rather than buried in the prose.
 */

const OPERATOR = '[Operator name]';
const CONTACT_EMAIL = 'support@example.com';
const JURISDICTION = '[jurisdiction]';
const EFFECTIVE = 'Effective 29 August 2026';

export default function TermsScreen() {
  return (
    <DocScreen title="Terms of Use" subtitle={EFFECTIVE}>
      <Section title="The short version">
        <Prose>
          Loom is a chat app that sends what you write to an AI model and shows you what comes back. You
          are responsible for what you send and for how you use what you get. The replies are generated
          text, not advice, and they are sometimes wrong. Do not treat them as a substitute for a
          professional.
        </Prose>
      </Section>

      <Section title="Who these terms are between">
        <Prose>
          These terms are an agreement between you and {OPERATOR}, who operates Loom. By creating an
          account or using the app you accept them. If you do not accept them, do not use the app.
        </Prose>
      </Section>

      <Section title="Your account">
        <Prose>
          An account needs a working email address. You get in with a code sent to that address, so
          keeping access to the mailbox is what keeps your account secure — anyone who can read your
          email can sign in as you. Tell us promptly if you think someone else has access.
        </Prose>
        <Prose>
          You must be old enough to agree to a contract where you live, and at least 13 in any case. If
          you are under 18, use the app with a parent or guardian.
        </Prose>
        <Prose>One person per account. Do not share your account or let someone else use it as you.</Prose>
      </Section>

      <Section title="What you may not do">
        <Bullets
          items={[
            'Break the law, or use the app to help someone else break it.',
            'Send content that infringes someone’s copyright, trademark, privacy or other rights.',
            'Upload other people’s personal information without a lawful reason to, or anything you are under an obligation to keep confidential.',
            'Try to get the model to produce material that sexualises children, incites violence, or facilitates serious harm.',
            'Attack the service: probe it, overload it, get around rate limits or authentication, or use it to attack anyone else.',
            'Use the code sandbox to mine cryptocurrency, scan or attack other systems, or work around its limits.',
            'Scrape the service, resell access to it, or use its output to train a competing model where that breaks the model provider’s terms.',
            'Impersonate anyone, or present generated text as something a real person said.',
          ]}
        />
        <Prose>
          We can suspend or close an account that does these things, and we can remove content. Where it
          is reasonable to do so, we will say why.
        </Prose>
      </Section>

      <Section title="Your content">
        <Prose>
          What you write and attach stays yours. You give us permission to store it, process it, and
          send it to the providers described in the Privacy Policy, for the purpose of running the app
          and answering you. That permission ends when you delete the content or your account, except
          where a provider or the law makes us keep something for a period.
        </Prose>
        <Prose>
          You keep whatever rights you have in a reply. Generated text may not be copyrightable
          everywhere, and a model can produce something close to what it produced for someone else, so
          treat a reply as yours to use rather than as yours exclusively. Check anything you intend to
          publish.
        </Prose>
      </Section>

      <Section title="AI replies">
        <Prose>
          Replies are generated by third-party models. They can be inaccurate, out of date, or confidently
          wrong, and the same question can give different answers. Nothing in a reply is medical, legal,
          financial or other professional advice.
        </Prose>
        <Prose>
          Verify anything you are going to act on. Where a reply cites sources, read them — a citation
          means a page was fetched, not that the summary of it is right.
        </Prose>
      </Section>

      <Section title="Running code">
        <Prose>
          Code from a reply runs in a disposable virtual machine, not on your device. It is still code
          you have chosen to run: read it first. We do not guarantee the sandbox contains everything, and
          you must not use it to reach systems you are not authorised to reach.
        </Prose>
      </Section>

      <Section title="Availability and changes">
        <Prose>
          The app is provided as it is. Features can change or be withdrawn, the available models are
          decided by upstream providers rather than by us, and there is no uptime commitment. We may
          impose usage limits, and we may change them.
        </Prose>
        <Prose>
          Some things in the app are unfinished and labelled as such in the Help Center. They are not a
          promise that they will ship.
        </Prose>
      </Section>

      <Section title="Paid features">
        <Prose>
          Loom currently charges nothing, and the Subscription row in Settings is not connected to
          anything. If paid plans are introduced, their price and terms will be shown before you are
          asked to pay, and any purchase will be handled by the app store you installed from, under its
          own refund rules.
        </Prose>
      </Section>

      <Section title="Ending it">
        <Prose>
          You can stop using Loom at any time, and you can ask us to delete your account and its data by
          emailing {CONTACT_EMAIL}. We can suspend or end your access if you break these terms, or if we
          stop operating the service. Deleting a chat, or your account, removes it from our database and
          cannot be undone.
        </Prose>
      </Section>

      <Section title="Liability">
        <Prose>
          To the extent the law allows, {OPERATOR} is not liable for indirect or consequential loss, for
          lost profits or data, or for anything arising from your reliance on a generated reply. Nothing
          here limits liability that cannot be limited — including for death or personal injury caused by
          negligence, or for fraud.
        </Prose>
        <Prose>
          Some jurisdictions do not allow the exclusions above. Where that is the case, they do not apply
          to you and your statutory rights are unaffected.
        </Prose>
      </Section>

      <Section title="Changes to these terms">
        <Prose>
          We may update these terms. The date at the top says when this version took effect. If a change
          materially reduces your rights we will give notice in the app before it applies. Continuing to
          use Loom after a change means you accept it.
        </Prose>
      </Section>

      <Section title="Governing law">
        <Prose>
          These terms are governed by the laws of {JURISDICTION}, and its courts have jurisdiction —
          without affecting any right you have to bring a claim where you live.
        </Prose>
      </Section>

      <Section title="Contact">
        <Prose>Questions about these terms: {CONTACT_EMAIL}.</Prose>
      </Section>
    </DocScreen>
  );
}
